"""
Stub file for c_utils module
"""

Card = tuple[int, int]

class GameState:
    def __init__(self) -> None:
        self.cards: list[int]
        self.lastMovePlayerId: int
        self.lastPlayedCards: list[Card]
        self.activePlayerFlag: list[bool]
        self.playerPassFlag: list[bool]

    def clearLastPlayedCards(self) -> None: ...
    def clearPlayerPassFlags(self) -> None: ...
    def countPlayerCards(self, playerId: int) -> int: ...
    def numActivePlayers(self) -> int: ...
    def numPlayersPassed(self) -> int: ...
    def update(self, playerId: int, playedCards: list[Card]) -> None: ...

def generateCandidateMoves(playerId: int, state: GameState) -> list[list[Card]]: ...
